DEBUG = True
SECRET_KEY = "SECRET_EXAMPLE_12345"
USE_SESSION_FOR_NEXT = True

MAIL_SERVER = "localhost"
MAIL_PORT = 25
MAIL_DEBUG = MAIL_SUPPRESS_SEND = DEBUG
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_DEFAULT_SENDER = "chili@ericoc.com"

TELEPHONE = "7577423742"
MAIL_RECIPIENT = "eric@ericoc.com"
MAIL_SUBJECT = "Chili"
COOKIE = "submitted"
